/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedProjectsRouteImport } from './routes/_authed.projects'
import { Route as AuthedEnvironmentRouteImport } from './routes/_authed.environment'
import { Route as AuthedDeploymentsRouteImport } from './routes/_authed.deployments'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedProjectsNewRouteImport } from './routes/_authed.projects.new'
import { Route as AuthedProjectsIdRouteImport } from './routes/_authed.projects.$id'
import { Route as AuthedDeploymentsIdRouteImport } from './routes/_authed.deployments.$id'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsRoute = AuthedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEnvironmentRoute = AuthedEnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeploymentsRoute = AuthedDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsNewRoute = AuthedProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedProjectsRoute,
} as any)
const AuthedProjectsIdRoute = AuthedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedProjectsRoute,
} as any)
const AuthedDeploymentsIdRoute = AuthedDeploymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedDeploymentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/deployments': typeof AuthedDeploymentsRouteWithChildren
  '/environment': typeof AuthedEnvironmentRoute
  '/projects': typeof AuthedProjectsRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/deployments/$id': typeof AuthedDeploymentsIdRoute
  '/projects/$id': typeof AuthedProjectsIdRoute
  '/projects/new': typeof AuthedProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/deployments': typeof AuthedDeploymentsRouteWithChildren
  '/environment': typeof AuthedEnvironmentRoute
  '/projects': typeof AuthedProjectsRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/deployments/$id': typeof AuthedDeploymentsIdRoute
  '/projects/$id': typeof AuthedProjectsIdRoute
  '/projects/new': typeof AuthedProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/deployments': typeof AuthedDeploymentsRouteWithChildren
  '/_authed/environment': typeof AuthedEnvironmentRoute
  '/_authed/projects': typeof AuthedProjectsRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/deployments/$id': typeof AuthedDeploymentsIdRoute
  '/_authed/projects/$id': typeof AuthedProjectsIdRoute
  '/_authed/projects/new': typeof AuthedProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/deployments'
    | '/environment'
    | '/projects'
    | '/settings'
    | '/auth/callback'
    | '/deployments/$id'
    | '/projects/$id'
    | '/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/deployments'
    | '/environment'
    | '/projects'
    | '/settings'
    | '/auth/callback'
    | '/deployments/$id'
    | '/projects/$id'
    | '/projects/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/deployments'
    | '/_authed/environment'
    | '/_authed/projects'
    | '/_authed/settings'
    | '/auth/callback'
    | '/_authed/deployments/$id'
    | '/_authed/projects/$id'
    | '/_authed/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects': {
      id: '/_authed/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedProjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/environment': {
      id: '/_authed/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof AuthedEnvironmentRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deployments': {
      id: '/_authed/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof AuthedDeploymentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/new': {
      id: '/_authed/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthedProjectsNewRouteImport
      parentRoute: typeof AuthedProjectsRoute
    }
    '/_authed/projects/$id': {
      id: '/_authed/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthedProjectsIdRouteImport
      parentRoute: typeof AuthedProjectsRoute
    }
    '/_authed/deployments/$id': {
      id: '/_authed/deployments/$id'
      path: '/$id'
      fullPath: '/deployments/$id'
      preLoaderRoute: typeof AuthedDeploymentsIdRouteImport
      parentRoute: typeof AuthedDeploymentsRoute
    }
  }
}

interface AuthedDeploymentsRouteChildren {
  AuthedDeploymentsIdRoute: typeof AuthedDeploymentsIdRoute
}

const AuthedDeploymentsRouteChildren: AuthedDeploymentsRouteChildren = {
  AuthedDeploymentsIdRoute: AuthedDeploymentsIdRoute,
}

const AuthedDeploymentsRouteWithChildren =
  AuthedDeploymentsRoute._addFileChildren(AuthedDeploymentsRouteChildren)

interface AuthedProjectsRouteChildren {
  AuthedProjectsIdRoute: typeof AuthedProjectsIdRoute
  AuthedProjectsNewRoute: typeof AuthedProjectsNewRoute
}

const AuthedProjectsRouteChildren: AuthedProjectsRouteChildren = {
  AuthedProjectsIdRoute: AuthedProjectsIdRoute,
  AuthedProjectsNewRoute: AuthedProjectsNewRoute,
}

const AuthedProjectsRouteWithChildren = AuthedProjectsRoute._addFileChildren(
  AuthedProjectsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDeploymentsRoute: typeof AuthedDeploymentsRouteWithChildren
  AuthedEnvironmentRoute: typeof AuthedEnvironmentRoute
  AuthedProjectsRoute: typeof AuthedProjectsRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDeploymentsRoute: AuthedDeploymentsRouteWithChildren,
  AuthedEnvironmentRoute: AuthedEnvironmentRoute,
  AuthedProjectsRoute: AuthedProjectsRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
